- name: Create a VM in AWS EC2
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/aws_flavors.yml

  tasks:
    - name: Create VM in AWS
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        count: 1
        wait: true
        tags:
          Name: "{{ instance_name }}"
      register: ec2_instance

    - name: Debug instance details
      ansible.builtin.debug:
        var: ec2_instance      