- name: Create a VM in AWS EC2 with Windows Server
  hosts: localhost
  gather_facts: false

  vars:
    security_group_name: windows-sg
  vars_files:
  - vars/aws_flavors.yml

  tasks:
    - name: Create security group for Windows instance
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        description: "Security group for Windows instance with WinRM and RDP access"
        region: "{{ aws_region }}"
        rules:
        - proto: tcp
          from_port: 5986
          to_port: 5986
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5985
          to_port: 5985
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 3389
          to_port: 3389
          cidr_ip: 0.0.0.0/0
      register: security_group

    - name: Create Windows EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ windows_ami_by_region[aws_region] }}"  # Windows AMI ID
        count: 1
        wait: true
        security_group: "{{ security_group_name }}"
        user_data: |
          <powershell>
          net user Administrator redhat123
          # Download and execute a PowerShell script from GitHub
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/AlmendraSalgado/ansible_windows/refs/heads/main/ConfigureRemotingForAnsible.ps1" -OutFile "C:\Users\Administrator\script.ps1"
          Start-Process -FilePath "powershell.exe" -ArgumentList "-ExecutionPolicy Bypass -File C:\Users\Administrator\script.ps1"
          </powershell>
        tags:
          Name: "{{ instance_name }}"
      register: ec2_instance
