- name: Create a VM in AWS EC2
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/aws_flavors.yml

  tasks:
    - name: Create security group for SSH access
      amazon.aws.ec2_security_group:
        name: "{{ aws_security_group_name | default('test-ansible-sg') }}"
        description: "{{ aws_security_group_description | default('Allow some ports for accessing the instance') }}"
        vpc_id: "{{ vpc_id | default(omit) }}"
        region: "{{ aws_region | default('us-east-2') }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 9090
            to_port: 9090
            cidr_ip: 0.0.0.0/0          
      register: security_group

    - name: Check if EC2 instance already exists
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region | default('us-east-2') }}"
        filters:
          "tag:Name": "{{ instance_name | default('vm1') }}"
      register: existing_instance

    - name: Create VM in AWS
      amazon.aws.ec2_instance:
        region: "{{ aws_region | default('us-east-2') }}"
        key_name: "{{ key_name | default('ec2key') }}"
        instance_type: "{{ instance_type | default('t2.micro') }}"
        image_id: "{{ rhel_ami_by_region[aws_region] }}"
        vpc_subnet_id: "{{ vpc_subnet_id | default(omit) }}"
        count: 1
        wait: true
        security_group: "{{ aws_security_group_name | default('test-ansible-sg') }}"
        tags:
          Name: "{{ instance_name | default('vm1') }}"
      register: ec2_instance
      # when: existing_instance.instances | length == 0

    - name: Debug instance details
      ansible.builtin.debug:
        var: ec2_instance   

    - name: Save for later information from ec2_instance
      ansible.builtin.set_stats:
        data:
          instance_name: "{{ instance_name | default('vm1')  }}"
          instance_id: "{{ ec2_instance.instance_ids[0] }}"
          ami_id: "{{ rhel_ami_by_region[aws_region] }}"
          public_ip: "{{ ec2_instance.instances[0].public_ip_address }}"

    - name: Wait for SSH to become available on the new EC2 instance
      ansible.builtin.wait_for:
        host: "{{ ec2_instance.instances[0].public_ip_address }}"
        port: 22
        timeout: 300
        state: started
