- name: Create a VM in AWS EC2
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/aws_flavors.yml

  tasks:
    - name: Create security group for SSH access
      amazon.aws.ec2_security_group:
        name: ssh-only-sg
        description: allow SSH access 
        vpc_id: "{{ vpc_id | default(omit) }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
      register: security_group

    - name: Create VM in AWS
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ rhel_ami_by_region[aws_region] }}"
        vpc_subnet_id: "{{ vpc_subnet_id | default(omit) }}"
        count: 1
        wait: true
        security_group: "ssh-only-sg"
        tags:
          Name: "{{ instance_name }}"
      register: ec2_instance

    - name: Debug instance details
      ansible.builtin.debug:
        var: ec2_instance   

    - name: Save for later information from ec2_instance
      ansible.builtin.set_stats:
        data:
          instance_name: "{{ instance_name }}"
          instance_id: "{{ ec2_instance.instance_ids[0] }}"
          ami_id: "{{ rhel_ami_by_region[aws_region] }}"
          public_ip: "{{ ec2_instance.instances[0].public_ip_address }}"
