- name: Create a VM in AWS EC2
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/aws_flavors.yml

  tasks:
    - name: Create VM in AWS
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_by_region[aws_region] }}"
        count: 1
        wait: true
        tags:
          Name: "{{ instance_name }}"
      register: ec2_instance

    - name: Debug instance details
      ansible.builtin.debug:
        var: ec2_instance   

    - name: Save for later information from ec2_instance
      ansible.builtin.set_stats:
        data:
          instance_name: "{{ instance_name }}"
          instance_id: "{{ ec2_instance.instance_ids[0] }}"
          ami_id: "{{ ami_by_region[aws_region] }}"
          public_ip: "{{ ec2_instance.instances[0].public_ip_address }}"
